### ISSUE TITLE
Question: how wireguard is routed through tor

### ISSUE THREAD

**Issue by NOXCIS** [shahradelahi/wireadmin#15]
Can you explain how wg is routed through tor?

**Comment by shahradelahi** [comment]
* [Transparently Routing Traffic Through Tor](https://gitlab.torproject.org/legacy/trac/-/wikis/doc/TransparentProxy)

https://github.com/wireadmin/wireadmin/blob/b8e8ddb4ce9413e6c3e0bf24450e1d4b6e7a9b46/web/src/lib/wireguard/index.ts#L619-L658

**Comment by NOXCIS** [comment]
@shahradelahi Nice, how do I upstream DNS to per say another container under the same docker net for filtering?

**Comment by shahradelahi** [comment]
Not sure what exactly you're asking, but in the official [Docker Docs: DNS Services](https://docs.docker.com/engine/network/#dns-services), there is enough detail about setting up DNS for containers.

In the `WireAdmin`, there is a service called `dnsmasq` on port `53`. It forwards the incoming DNS queries to the `Tor` on port `53530`.

**Comment by NOXCIS** [comment]
@shahradelahi check Wiregate repo on my profile. I need to figure out how to allow peers access to a local docker network while being wrouted through tor. Got the tor routing part.

**Comment by shahradelahi** [comment]
In the `iptables`, instead of dropping the traffic for local addresses ([`Reserved Addresses`](https://gitlab.torproject.org/legacy/trac/-/wikis/doc/TransparentProxy#reserved-blocks)) to Tor, you can reroute them to the default network interface.

https://github.com/wireadmin/wireadmin/blob/b8e8ddb4ce9413e6c3e0bf24450e1d4b6e7a9b46/web/src/lib/wireguard/index.ts#L650

If you send a request using the hostname, it won't work because the DNS queries are resolved by Tor, which doesn't know the destination if it's a route provided by your router.

You must not use the Tor DNS or provide static hosts in the `Dnsmasq` config file. The `/etc/hosts` file might work as well.

**Comment by NOXCIS** [comment]
@shahradelahi got it working Tor with ODOH dns with adguard,unbound and dnscrypt. Via WireGuard. Thanks man. Didn't follow those last instructions btw. ![image](https://github.com/user-attachments/assets/ee5fabab-3890-44b5-91c0-7ff1cf522ea2)

**Comment by NOXCIS** [comment]
Thanks again, I took your idea to the extream for WGDashboard over on [Wiregate](https://github.com/NOXCIS/Wiregate/tree/amneziawg) so i might as well give back. The Tor Plugin binarys are built daily from source over on this repo https://github.com/NOXCIS/Docker-Tor-Transports. 


```yaml

services:

  wg-dashboard:
    image: noxcis/wg-dashboard:terra-fuego-beta
    container_name: wg-dashboard
    hostname: wg-dashboard
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    volumes:
      - wgd_configs:/etc/wireguard 
      - wgd_db:/opt/wireguarddashboard/src/db 
      - wgd_db:/opt/wireguarddashboard/src/dashboard_config

    environment:
    #Use Ofuscated Wireguard (AmneziaWG)
      - AMNEZIA_WG=true
    #Set Timezone
      - TZ=America/Chicago

    #Tor Settings 
    ##########################################################
      - WGD_TOR_PROXY=false
      - WGD_TOR_EXIT_NODES={ch}
      - WGD_TOR_DNS_EXIT_NODES={gb}
      - WGD_TOR_PLUGIN=snowflake #OPTIONS webtunnel, obfs4, snowflake
      - WGD_TOR_BRIDGES=false

    #WGDashboard Global Settings
    ##########################################################
      - WGD_WELCOME_SESSION=false
      - WGD_AUTH_REQ=false
      - WGD_USER=admin
      - WGD_PASS=admin
      - WGD_REMOTE_ENDPOINT=0.0.0.0
      - WGD_REMOTE_ENDPOINT_PORT=80
      - WGD_PEER_ENDPOINT_ALLOWED_IP=0.0.0.0/0
      - WGD_KEEP_ALIVE=21
      - WGD_MTU=1420
      - WGD_PORT_RANGE_STARTPORT=4430

    #DNS Setiings Must Match
    ##########################################################
      - WGD_DNS="1.1.1.1, 1.0.0.1"
      - WGD_IPTABLES_DNS=1.1.1.1

      
    #Obfuscated Wireguard via AmneziaWG Junk Headder Settings
    #All parameters should be the same between Client and Server, except Jc - it can vary.
    #########################################################
      - WGD_JC=5 #Jc — 1 ≤ Jc ≤ 128; recommended range is from 3 to 10 inclusive
      - WGD_JMIN=500 #Jmin — Jmin < Jmax; recommended value is 50
      - WGD_JMAX=550 #Jmax — Jmin < Jmax ≤ 1280; recommended value is 1000
      - WGD_S1=30 #S1 — S1 < 1280; S1 + 56 ≠ S2; recommended range is from 15 to 150 inclusive
      - WGD_S2=40 #S2 — S2 < 1280; recommended range is from 15 to 150 inclusive
      - WGD_H1=123456 #H1/H2/H3/H4 — must be unique among each other; recommended range is from 5 to 2147483647 inclusive
      - WGD_H2=67543 #H2
      - WGD_H3=32345 #H3
      - WGD_H4=123123 #H4
    ports:
      - "4430-4433:4430-4433/udp" #UDP Interface Listen Ports
      - 8000:80/tcp #Comment Out for full network lockdown
      #Access the dashboard @ localhost:8000
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

volumes:
    wgd_configs:
    wgd_db:
    
```

```Dockerfile

# builder: FRONTEND - Vite Builder 
FROM  --platform=${BUILDPLATFORM} node:iron-alpine3.20 AS builder
WORKDIR /opt/wireguarddashboard/src/static/app
COPY ./src/static /opt/wireguarddashboard/src/static 
RUN npm install && \                
    npm update && \                
    npm run build  && \              
    rm -r ./node_modules && \
    rm -r /opt/wireguarddashboard/src/static/app/src


# pybuild: BACKEND - WG-Dash Builder for Brcypt & Psutil Binary (Python)
FROM  alpine:latest AS pybuild
RUN apk add --no-cache sudo gcc musl-dev rust cargo linux-headers
WORKDIR /opt/wireguarddashboard/src
COPY ./build_scripts/builder.sh ./build_scripts/builder_requirements.txt /opt/wireguarddashboard/src/
RUN chmod u+x ./builder.sh && ./builder.sh 


# Stage 3: Final image
FROM alpine:latest
LABEL maintainer="NOXCIS"
ENV TZ=UTC
WORKDIR /opt/wireguarddashboard/src

COPY ./src /opt/wireguarddashboard/src/

#Copy Built Bcrypt & Psutil Binarys
COPY --from=pybuild /opt/wireguarddashboard/src/venv /opt/wireguarddashboard/src/venv
COPY --from=pybuild /opt/wireguarddashboard/src/log /opt/wireguarddashboard/src/log

#Copy Built Frontend  
COPY --from=builder /opt/wireguarddashboard/src /opt/wireguarddashboard/src

#Tor Client Transport Plugins
COPY --from=noxcis/tor-bins:latest /lyrebird /usr/local/bin/lyrebird
COPY --from=noxcis/tor-bins:latest /webtunnel /usr/local/bin/webtunnel
COPY --from=noxcis/tor-bins:latest /snowflake /usr/local/bin/snowflake

#AmneziaWG Substitute install for WireGuard
COPY --from=noxcis/awg-bins:latest /amneziawg-go /usr/bin/amneziawg-go
COPY --from=noxcis/awg-bins:latest /awg /usr/bin/awg
COPY --from=noxcis/awg-bins:latest /awg-quick /usr/bin/awg-quick


#Entrypoint
RUN apk add --no-cache wireguard-tools bash sudo iptables tzdata && \
    apk upgrade && \
    chmod u+x /opt/wireguarddashboard/src/entrypoint.sh 


HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 CMD \
    sh -c 'pgrep gunicorn > /dev/null && pgrep tail > /dev/null' || exit 1

ENTRYPOINT ["/opt/wireguarddashboard/src/entrypoint.sh"]
#CMD ["docker_start"]

STOPSIGNAL SIGTERM


```


WireGuard Wireshark Packet Inspection Results
![WireGuard Wireshark Results](https://i.imgur.com/D9VyKeL.png)

AmneziaWG Packet Inspection Results
![enter image description here](https://i.imgur.com/2N0Zjfe.png)
